### ISSUE TITLE
suicide命令仅在服务器上与OpenBlocks的墓碑不兼容

### ISSUE THREAD

**Issue by kuzuanpa** [Nova-Committee/Neutron#3]
游戏版本：1.7.10
服务端：forge-1.7.10-10.13.4.1614-1.7.10-universal.jar

复现方法：设置正确的服务端和客户端环境，仅安装OpenBlocks及其前置OpenModLib以及本mod
在客户端使用/suicide,身上的所有物品会消失，同时墓碑也不会生成，聊天栏提示“在执行此指令时出现了未知的错误”

服务端报错：
```
[Server thread/ERROR]: Couldn't process command: 'suicide'
java.lang.NoSuchMethodError: net.minecraft.util.IChatComponent.func_150254_d()Ljava/lang/String;
        at committee.nova.neutron.util.Utilities$Player$$anon$1.func_151519_b(Utilities.scala:75) ~[Utilities$Player$$anon$1.class:?]
        at net.minecraft.util.CombatTracker.func_151521_b(SourceFile:100) ~[rn.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:406) ~[mw.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855) ~[sv.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1034) ~[yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:491) ~[mw.class:?]
        at committee.nova.neutron.server.command.impl.CommandPlayer$Suicide.func_71515_b(CommandPlayer.scala:64) ~[CommandPlayer$Suicide.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by VulpesStella** [comment]
邪门了
